// Generate og-universes.js at build time from catalog.js
// This replaces the hardcoded UNIVERSE_MAP and INSIGHTS_MAP in api/og.js

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// Read catalog.js as text and extract UNIVERSE_CATALOG via a simple eval
const catalogPath = resolve(ROOT, 'src/data/catalog.js')
const catalogSrc = readFileSync(catalogPath, 'utf8')

// Extract UNIVERSE_CATALOG array — find it between the = and the first trailing ;
const catalogMatch = catalogSrc.match(/const UNIVERSE_CATALOG\s*=\s*(\[[\s\S]*?\]);?\s*$/m)
if (!catalogMatch) {
  throw new Error('Could not find UNIVERSE_CATALOG in catalog.js')
}

let UNIVERSE_CATALOG
try {
  // Use Function constructor to safely eval the array literal (same as JSON.parse for arrays)
  UNIVERSE_CATALOG = new Function(`return ${catalogMatch[1]}`)()
} catch (e) {
  throw new Error(`Failed to parse UNIVERSE_CATALOG: ${e.message}`)
}

// Build UNIVERSE_MAP
const UNIVERSE_MAP = {}
for (const entry of UNIVERSE_CATALOG) {
  UNIVERSE_MAP[entry.id] = {
    anime: entry.anime,
    tagline: entry.tagline,
    visualizationHint: entry.visualizationHint,
    themeColors: { primary: entry.themeColors.primary },
  }
}

// INSIGHTS_MAP — kept in sync manually since it's editorial content not in catalog.js
const INSIGHTS_MAP = {
  insights: { title: 'System Breakdowns', tagline: 'Deep dives into how anime worlds actually work.', themeColor: '#22d3ee' },
  'one-piece-power-economy': { title: 'Why the One Piece World Is Designed Like an Economy', tagline: 'The Yonko system, maritime trade routes, and Devil Fruit markets.', themeColor: '#dc2626' },
  'naruto-chakra-meritocracy': { title: 'Chakra as a Bureaucratic Resource', tagline: 'How shinobi villages turned personal energy into a labor market.', themeColor: '#f59e0b' },
  'jjk-cursed-energy-thermodynamics': { title: "Cursed Energy as an Inverse Heat Engine", tagline: "Why Gojo's Infinity works like a thermodynamic paradox.", themeColor: '#7c3aed' },
  'aot-determinism-chaos': { title: 'The Determinism Engine in Attack on Titan', tagline: 'Why every freedom fight circles back to the same trap.', themeColor: '#6b7280' },
  'hxh-nen-specialization': { title: 'Why Nen Is the Best Magic System in Anime', tagline: 'Vow and Limitations as a self-limiting growth protocol.', themeColor: '#16a34a' },
  'death-note-killing-archetype': { title: 'Death Note as a Tool Critique', tagline: 'The notebook as a mirror for power fantasies.', themeColor: '#1e293b' },
  'demonslayer-breathing-economics': { title: 'Breathing Forms as Weaponized Poetry', tagline: 'How swordsmanship became a language system.', themeColor: '#0ea5e9' },
  'chainsawman-devil-economy': { title: 'Why Devil Contracts Are a Raw Deal', tagline: 'Fear as fuel, trauma as currency.', themeColor: '#dc2626' },
  'anime-power-systems-ranked': { title: 'All Power Systems, Ranked by Architectural Complexity', tagline: 'The definitive ranking of anime magic systems.', themeColor: '#22d3ee' },
  'best-anime-worldbuilding': { title: 'Best Anime Worldbuilding: 5 Universes Where the World Is the Main Character', tagline: 'These 5 universes have the most architecturally complete worldbuilding.', themeColor: '#22d3ee' },
  'lore-vs-sys-explained': { title: 'LORE vs SYSTEM Explained', tagline: 'What makes an anime universe a system and not just a setting.', themeColor: '#22d3ee' },
}

// Generate the output file
const outputPath = resolve(ROOT, 'api/og-universes.js')
const universeEntries = Object.entries(UNIVERSE_MAP)
  .map(([id, data]) => `  ${id}: { anime: ${JSON.stringify(data.anime)}, tagline: ${JSON.stringify(data.tagline)}, visualizationHint: ${JSON.stringify(data.visualizationHint)}, themeColors: { primary: ${JSON.stringify(data.themeColors.primary)} } }`)
  .join(',\n')

const insightEntries = Object.entries(INSIGHTS_MAP)
  .map(([id, data]) => `  ${id}: { title: ${JSON.stringify(data.title)}, tagline: ${JSON.stringify(data.tagline)}, themeColor: ${JSON.stringify(data.themeColor)} }`)
  .join(',\n')

const output = `// AUTO-GENERATED by scripts/generate-og-map.js — do not edit manually
export const UNIVERSE_MAP = {
n${universeEntries}
}

export const INSIGHTS_MAP = {
n${insightEntries}
}
`

writeFileSync(outputPath, output, 'utf8')

const universeCount = Object.keys(UNIVERSE_MAP).length
const insightCount = Object.keys(INSIGHTS_MAP).length
console.log(`✓ Generated api/og-universes.js (${universeCount} universes, ${insightCount} insights)`)
